/*
 * This file is generated by jOOQ.
 */
package com.odyssey.booktube.database.jooq.model.book_tube;


import com.odyssey.booktube.database.jooq.model.DefaultCatalog;
import com.odyssey.booktube.database.jooq.model.book_tube.tables.Author;
import com.odyssey.booktube.database.jooq.model.book_tube.tables.Book;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookTube extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>book_tube</code>
     */
    public static final BookTube BOOK_TUBE = new BookTube();

    /**
     * The table <code>book_tube.Author</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>book_tube.Book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * No further instances allowed
     */
    private BookTube() {
        super("book_tube", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR,
            Book.BOOK
        );
    }
}
