/*
 * This file is generated by jOOQ.
 */
package com.odyssey.booktube.database.jooq.model.book_tube;


import com.odyssey.booktube.database.jooq.model.book_tube.tables.Author;
import com.odyssey.booktube.database.jooq.model.book_tube.tables.Book;


/**
 * Convenience access to all tables in book_tube.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>book_tube.Author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>book_tube.Book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
