/*
 * This file is generated by jOOQ.
 */
package com.odyssey.booktube.database.jooq.model;


import com.odyssey.booktube.database.jooq.model.book_tube.BookTube;

import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>book_tube</code>.
     */
    public final BookTube BOOK_TUBE = BookTube.BOOK_TUBE;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(
            BookTube.BOOK_TUBE
        );
    }
}
